### ISSUE TITLE
Include auto-compile option

### ISSUE THREAD

**Issue by dusty-phillips** [chrivers/pyjaco#3]
Eventually, I would like to see a coffeescript-like autocompiler that watches for python files in one directory to be changed, and automatically compiles them to Javascript in another directory.

http://coffeescript.org/#usage

**Comment by chrivers** [comment]
I can certainly see the utility for that. What I do currently, is serve dynamically-compiled pyjaco code through a WSGI I wrote. It would be nice to have other solutions as well. I'm working on other things at the moment, but Patches Welcome :-)

**Comment by dusty-phillips** [comment]
I am just starting to understand the code, but I'll probably be able to submit a patch. Is the WSGI available on github or anywhere, for reference?

**Comment by chrivers** [comment]
Not as such, because it's part of another project. However, it's quite simple. This is the gist of it:

(init: self.v = pyjaco.Compiler([])

```
def code(self, method, title = None):
    self.pyjaco_code.append(self.v.compile_method(method, title, True))

def data(self, key, value):
    self.pyjaco_data.append(self.v.compile_data(key, value))
```

Then pyjaco_data and pyjaco_code contains lists that can be "\n".join()'ed, for example.

If you need more references for how the compiler interface works, you can look at pyjs.py and htmltest.py. I hope this helps?

**Comment by dusty-phillips** [comment]
A code monitor that works for me is in the patches at https://github.com/chrivers/pyjaco/pull/6

**Comment by dusty-phillips** [comment]
Since pull request #6 is also issue #6, this is now a duplicate of Issue 6.
