### ISSUE TITLE
abs() 

### ISSUE THREAD

**Issue by dusty-phillips** [chrivers/pyjaco#38]
Implement abs using Math.abs. 

Dusty will take this, it should be a good introduction to stdlib hacking. :)

**Comment by chrivers** [comment]
Awesome :)

Let me know if you need any help at all. The file you're looking for is stdlib/10-builtins.js

**Comment by dusty-phillips** [comment]
On 10/01/12 04:44 AM, Christian Iversen wrote:

> Awesome :)
> 
> Let me know if you need any help at all. The file you're looking for
> is stdlib/10-builtins.js

I implemented it in short order, but was wondering how accurate the 
exceptions have to be. If I call abs("somestring") in python, in raises 
a TypeError, for example. I set up my js code to throw 
py_builtins.TypeError, so the exceptions are the same. However, it 
appears that the type() command is not implemented yet, so I was not 
able to include the type in the error message, as occurs in Python. So 
while TypeError is thrown in both cases, the exception message is not 
the same.

Thoughts?

Dusty

**Comment by chrivers** [comment]
Error checking is one of the extremely tricky areas that I honestly doubt we'll ever emulate 100%, because often the compiler or python bytecode runner generates the exceptions. We just can't do that many checks in JavaScript without slowing everything down too much.

However, as for the type name, there's a very simple workaround: read the name directly: "foo.PY$**class**.PY$**name**"

**Comment by chrivers** [comment]
Github ate my code. What I meant was:

`foo.PY$__class__.PY$__name__`

**Comment by dusty-phillips** [comment]
Got that one. I have one more best practice question.

in python, abs("5") will error, whereas in javascript, Math.abs("5") will silently coerce the string to a number.

In order to make my abs function behave the same as python, I need to check if the input is really a number. Do you have a reliable way to do this?

I've considered ensuring typeof(js(value)) == "number", or testing the type in python code, but I feel I may be missing edge cases; have you already encountered this issue in other functions, and how did you compensate for it?

**Comment by chrivers** [comment]
Very good question indeed.

When not otherwise specified (`__getitem__` and `__getattr__` are special cases, for instance), the stdlib concerns itself /only/ with Python types.

In Python, `abs()` works on int and float by default, but this is merely because these types have `__abs__`.

So, we should implement `__abs__` in our types as well. Here's an example of `__abs__` in a custom class, and indeed it works like you would expect:

``` python
>>> class Foo(object):
...   def __abs__(self):
...     return 42
... 
>>> f = Foo()
>>> abs(f)
42
```

So my idea for an implementation is this: do `PY$__getattr__("abs")` on the type. If that fails, return a `TypeError`. Otherwise, return the result of calling this returned function.

**Comment by dusty-phillips** [comment]
Ok, I'm implementhing it this way, and adding **abs** calls to the int and float classes. complex() and long() will also require **abs** methods at some point, but I think we can consider those as part of the issues for those objects.

**Comment by chrivers** [comment]
Excellent. I'm doing some restructuring right now, including a just-now pushed sorting of the functions in 10-builtin.js, since it was a real mess. 

It might cause some pain now, but it's for the better in the long run. You probably want to pull, although carefully :)

**Comment by chrivers** [comment]
(and I agree. This is the really nice thing about the `__foo__` design. We can make the basic implementation, and postpone some of the details if we want)

**Comment by chrivers** [comment]
I've implemented it in the devel branch.
