### ISSUE TITLE
False != false?

### ISSUE THREAD

**Issue by dusty-phillips** [chrivers/pyjaco#8]
As an outsider to pyjaco, I'd like to discuss my surprise that the boolean False in python does not map directly to the boolean false in javascript. I'm not necessarily requesting a change, but I'd like to understand the design decisions. The following python compiles to the javascript below it using the pyjs.py script I have written, which uses Compiler.append_string. I don't know if other compile methods behave differently? If so, why?

``` python
@JSVar("alert")
def submit_add_form(ev):
    alert('submitted')
    return False
```

compiles to:

```
var submit_add_form = function() {
    var __kwargs = __kwargs_get(arguments);
    var __varargs = __varargs_get(arguments);
    var $v3 = Array.prototype.slice.call(arguments).concat(js(__varargs));
    var ev = ('ev' in __kwargs) ? __kwargs['ev'] : $v3[0];
    delete __kwargs.ev
    alert("submitted");
    return False;
}
```

In this case, the False return is supposed to stop the propagation of the submit event to the form handler, the function is hooked up to the jquery submit function on a form. Because it is returning the py-builtins object False instead of the boolean false, the event propagation is NOT stopped as I would expect from this code.

Is this intended behavior, and if so, what is the best practice for dealing with situations like this? I have determined that I can return false without defining false and it works correctly. However, I don't feel this is optimal, as my original code is not valid python anymore.

**Comment by chrivers** [comment]
You are absolutely right, False != false, and yes, this is confusing.

The problem is that "false", (the javascript bool val) does not support any of the operations that the python versions supports. On the other hand, "False", (the python version) does support these.

The correct way, for now, is to do this:

def foo(...)
   ....
   return js(False)

It looks a bit ugly, yes, but it works, and it makes your intention quite clear.

In the future, additional work on our multiplexing compiler will make the compiler automatically call js() when going python-to-javascript, and call py() when going the other way.

Until then, unfortunately, you have to manually tag your intent.

Beware! The oppposite is also true (and True, heh). If you get a javascript value, you need to call py() on it.

Many functions in the stdlib will allow both js and py types (chiefly, **getattr** and **getitem** for  performance reasons), so this might hide the fact that you really should convert it every time.

Trust me, it's a high priority to get this mess sorted out, it just takes quite a bit of work, but it's possible :-)

**Comment by chrivers** [comment]
For example, the py Bool type has **neg**, **nonzero**, **int** and so on. These are used all over the stdlib to match the python semantics.

I wont rule out that we might be able to rewrite the stdlib so it again maps back to primitive types, but it would be a lot of work, with many downsides. When we get the multiplexer infrastructure properly set up, it will solve it for us.

**Comment by chrivers** [comment]
(Oh, and it's the same thing for integers, floats and so on, but for those, there are even more **foo** functions that implement python semantics, so it's certainly impossible to avoid completely)

**Comment by dusty-phillips** [comment]
Thanks for the explanation. The js() "workaround" is what I'm looking for right now. I'm glad that future iterations will automate the process.
