### ISSUE TITLE
string.replace enters infinite loop

### ISSUE THREAD

**Issue by obeleh** [chrivers/pyjaco#80]
"a".replace("a", "ab")

will loop forever

**Comment by chrivers** [comment]
Hello. First of all, sorry for the _very_ long time it took to get back to you.

Pyjaco has recently seen a massive increase in activity, and we are working to release the new and much-improved version 2.0.

I'm happy to let you know that this bug is fixed in the new version. You can try it out already by cloning the "ist/compiler"-branch. Thanks for helping improve pyjaco :)
